FROM ubuntu:20.04

LABEL SOFTWARE_NAME samtools 1.12
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "samtools 1.12"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN     apt-get clean && \
		rm -r /var/lib/apt/lists/*

# reset APT block
RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && apt-get upgrade -y --fix-missing

RUN		apt-get update && apt-get install -y \
            build-essential \
            git \
            libbz2-dev \
            libcurl4-openssl-dev \
            liblzma-dev \
            libncurses-dev \
            python3-matplotlib \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-plain-generic \
            wget \
            zlib1g-dev

RUN     git clone \
            https://github.com/samtools/htslib.git \
            /htslib && \
        git clone \
            https://github.com/samtools/samtools.git \
            /samtools && \
        git clone \
            https://github.com/samtools/bcftools.git \
            /bcftools


WORKDIR /htslib
RUN     git checkout -f 1.12 &&\
        git submodule update --init --recursive
RUN     make -j && make install

WORKDIR /samtools
RUN     git checkout -f 1.12 &&\
        git submodule update --init --recursive
RUN     make -j && make install

WORKDIR /bcftools
RUN     git checkout -f 1.12 &&\
        git submodule update --init --recursive
RUN     make -j && make install

WORKDIR /

RUN	    rm -r /htslib /samtools /bcftools

ENTRYPOINT ["/usr/local/bin/samtools"]
